# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzaingredient',
            options={'verbose_name': 'Pizza ingredient', 'verbose_name_plural': 'Pizza ingredients'},
        ),
        migrations.AlterField(
            model_name='pizzaingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
