# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190312_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientscategory',
            name='is_dough',
            field=models.BooleanField(default=False),
        ),
    ]
