# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinbasket',
            options={'verbose_name': 'Ingredient in basket', 'verbose_name_plural': 'Ingredients in basket'},
        ),
        migrations.AlterModelOptions(
            name='pizzaingredientinorder',
            options={'verbose_name': 'Ingredient in order', 'verbose_name_plural': 'Ingredients in orders'},
        ),
        migrations.AlterField(
            model_name='ingredientsinbasket',
            name='nmb',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
        migrations.AlterField(
            model_name='pizzaingredientinorder',
            name='nmb',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
